MASTER----------------------

puts "AQUI VÃO OS CODIGOS DO MASTER"
puts "CODIGO MASTER FINAL PARA O TESTE DERRADEIRO"



KA-----------------------
puts "NOVOS CODIGOS DA KA QUE NAO INTERFEREM EM NADA COM O MASTER"


GUI----------------------
puts "NOVOS CODIGOS FEITOS PARA O BRANCH DO GUI. VAMOS LÁ"

puts "AQUI VAI O TESTE FINAL DO TEMA BRANCH"

puts "TESTE DE REBASE"